import pytest
import shutil

from pathlib import Path

class Tests:
    """ Class used to setup Pytest testing environments
    """

    @pytest.fixture(autouse=True)
    def setup_teardown(self, tmpdir):
        """ Setup and teardown before any tests

        :param tmpdir: auto created Pathlib reference to TMPdir generated by Pytest
        """

        self.tmpdir = Path(tmpdir)
        self.password = 'mootoothree'  # PW of vault encrypted content
        self.group_vars = self.tmpdir / 'group_vars'

        testplay = Path('tests/testplay')

        # Copy files from testplay to tmpdir
        shutil.copytree(testplay, tmpdir, dirs_exist_ok=True)

        yield  ## Execute test

        # Remove tmpdir
        shutil.rmtree(tmpdir)

    def _get_content(self, path):
        """ Get content from file

        :param path: Pathlib object to open to get content from file
        :return: List of lines in file
        """
        with path.open('r') as f:
            return f.readlines()
